/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.cargal.littlecalc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class LittleCalcTest {
    @Test void testAppHasAGreeting() {
        var classUnderTest = new LittleCalc();
        assertEquals(classUnderTest.getClass(),LittleCalc.class);
    }
}
