/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.cargal.littlecalc;

import org.junit.Test;
import static org.junit.Assert.*;

public class LittleCalcTest {
    @Test public void testAppHasAGreeting() {
        var classUnderTest = new LittleCalc();
        
    }
}
